import { Droplets, Settings, Zap, Target, Flame, Gauge } from "lucide-react";
import { Link } from "@/i18n/routing";

export const categories = [
  { id: "all", name: "All Products" },
  { id: "tension", name: "Surface Tension" },
  { id: "foam", name: "Foam Analysis" },
  { id: "rheology", name: "Interface Rheology" },
  { id: "accessories", name: "Accessories" },
];

export const products = [
  {
    productKey: "trackerTensiometer",
    title: "TRACKER™ Tensiometer",
    description:
      "The Most Powerful and Versatile Optical Drop Tensiometer & Interfacial Rheometer to study surfaces and interfaces.",
    features: [
      "Drop shape analysis (DSA)",
      "Real-time measurements",
      "Temperature control up to 200°C",
      "Automated dispensing system",
      "High-resolution imaging",
    ],
    category: "tension",
    price: "Contact for Quote",
    image: "/images/products/Tracker-tensiometer.avif",
    path: "/products/trackertensiometer",
    pdfUrl:"/pdf/TEST.pdf"
  },
  {
    productKey: "foamscan",
    title: "FOAMSCAN™ Foam Analyzer",
    description:
      "The most accurate Foam analyzer to characterize Liquid foams properties and test defoamers effectiveness.",
    features: [
      "Foam height tracking",
      "Bubble size distribution",
      "Liquid content measurement",
      "Multi-sample analysis",
      "Automated reporting",
    ],
    category: "foam",
    price: "Contact for Quote",
    image: "/images/products/foamscan-foam-analyzer.avif",
    path: "/products/foamscan",
    pdfUrl:"/pdf/TEST.pdf",
  },
  {
    productKey: "bubbleStatistics",
    title: "BubbleStatistics™ Software",
    description:
      "Foam structure statistical analysis software to measure bubbles size and distribution",
    features: [
      "Oscillatory measurements",
      "Frequency sweep capability",
      "Temperature control",
      "Real-time monitoring",
      "Advanced analysis software",
    ],
    category: "rheology",
    price: "Contact for Quote",
    video: "/images/products/bubblestatsvideo.mp4",
    path: "/products/bubbleanalyser",
    pdfUrl:"/pdf/TEST.pdf"
  },
  {
    productKey: "foamscanHTMP",
    title: "FoamScan™ High Temperature Mid Pressure (HTMP)",
    description:
      "Optical drop Tensiometer and Interfacial rheometer for high temperature and pressure measurements",
    features: [
      "Compact design",
      "Battery operation",
      "Wireless connectivity",
      "Cloud data storage",
      "Easy operation",
    ],
    category: "tension",
    price: "Contact for Quote",
    image: "/images/products/tracker-h-mobile.avif",
    path: "/products/trackerhtp",
    pdfUrl:"/pdf/TEST.pdf"
  },
  {
    productKey: "trackerHTHP",
    title: "Tracker™ High Temperature Pressure (HTHP)",
    description:
      "Foam analyzer for high-temperature and mid-pressure measurements",
    features: [
      "Temperature range: -10°C to 200°C",
      "±0.1°C accuracy",
      "Rapid heating/cooling",
      "Compatible with all instruments",
      "Remote monitoring",
    ],
    category: "accessories",
    price: "Contact for Quote",
    image: "/images/products/temperature-control-module.avif",
    path: "/products/foamscanhtmp",
    pdfUrl:"/pdf/TEST.pdf"
  },
  {
    productKey: "jetscan",
    title: "JETSCAN™ Defoamer Tester",
    description: "High-Through-Put Defoamer Tester.",
    features: [
      "Micro-drop capability",
      "Contact angle measurement",
      "High magnification optics",
      "Automated analysis",
      "Research-grade precision",
    ],
    category: "tension",
    price: "Contact for Quote",
    image: "/images/products/microtrac-drop-shape-analyzer.avif",
    path: "/products/jetscan",
    pdfUrl:"/pdf/TEST.pdf"
  },
];

// Foamscam


export const generationModes = [
    {
      icon: Droplets,
      title: "Gas Sparging",
      description: "Foam generated by injecting gas through a porous glass filter at controlled flow rate."
    },
    {
      icon: Settings,
      title: "Mechanical Stirring",
      description: "Foam generated by agitating the liquid in a stirring chamber at controlled speed."
    },
    {
      icon: Zap,
      title: "External Generation",
      description: "Analyze foam produced by any external device or process."
    }
  ];

  export const foamingProperties = [
    "Foam Volume (mL)",
    "Liquid volume (mL)",
    "Gas volume (mL)",
    "Foam Wetness (%)",
    "Foam Capacity",
    "Foam Expansion",
    "Foam Density",
    "Antifoam effectiveness (mL)"
  ];

  export const stabilityProperties = [
    "Foam Volume decay (mL)",
    "Drainage (% liquid fraction)",
    "Foam volume half-lifetime (sec)",
    "Liquid stability half-lifetime (sec)",
    "Foam stability index",
    "Defoamer persistence (sec)"
  ];

  export const applications = [
    "Foamability of daily products: body care, cosmetics, food, barista, beer, sodas",
    "Product Formulation: surfactants screening, quality improvement, reducing raw materials",
    "Foaming and Wetting properties for Cleaning and coating products",
    "Expansion and foam insulation properties of Firefighting foams",
    "Creating solid foam structure for construction materials",
    "Absorbing or applying pressures for natural resources extraction",
    "Froth flotation as a method for separating solids",
    "Foam-Assisted Chemical Flooding for Enhanced Oil Recovery",
    "Foam-reducing agents and Anti-foams effectiveness"
  ];


export const jetscan = {

  features : [
    "Foam generation by liquid jet circulation",
    "Image analysis with TECLIS software",
    "Temperature control up to 90°C",
    "100% software-controlled operations",
    "Automated defoamer injection (up to 28 samples)",
    "Effectiveness measurement (knock down effect)",
    "Persistence measurement capability",
    "Automatic cleaning after each test"
  ],

  applications : [
    {
      title: "Food & Beverage Production",
      description: "Defoamer testing for production, processing, packaging, and dispensing applications."
    },
    {
      title: "Laundry Detergent Manufacturing",
      description: "Antifoam effectiveness evaluation for detergent formulation and production optimization."
    },
    {
      title: "Paper Industry & Bio-sourced Materials",
      description: "Foam control solutions for paper production and sustainable material processing."
    },
    {
      title: "Industrial Wastewater Treatment",
      description: "Defoamer testing for efficient wastewater management and treatment processes."
    },
    {
      title: "Home & Personal Care",
      description: "Foam control assessment for cosmetics, cleaning products, and personal care formulations."
    },
    {
      title: "Paints & Varnishes",
      description: "Antifoam agent testing for coating formulations to prevent foam formation during application."
    }
  ],

   specifications : [
    { parameter: "Temperature Range", value: "Up to 90°C" },
    { parameter: "Control System", value: "100% software controlled" },
    { parameter: "Foam Generation Method", value: "Liquid jet circulation" },
    { parameter: "Analysis Technique", value: "Image analysis + TECLIS software" },
    { parameter: "Defoamer Capacity", value: "Up to 28 samples" },
    { parameter: "Measurement Parameters", value: "Temperature, liquid volume, flow rate" },
    { parameter: "Automation Level", value: "Fully automated testing" },
    { parameter: "Cleaning", value: "Automatic system cleaning" }
  ],

   capabilities : [
    {
      icon: Droplets,
      title: "Jet Circulation System",
      description: "Foam generation through controlled liquid jet circulation with precise flow rate management."
    },
    {
      icon: Target,
      title: "Effectiveness & Persistence",
      description: "Measures knock down effect and time to maximum foam height with defoamer present."
    },
    {
      icon: Zap,
      title: "High-Throughput Testing",
      description: "Fully automated testing of up to 28 defoamer samples with automatic cleaning cycles."
    }
  ]
}

export const trackerhtp = {

   features : [
    "Temperature up to 200°C",
    "Pressure up to 700 bar",
    "High pressure cell certified by CETIM",
    "Interfacial tension (Liquid/Liquid) measurements",
    "Superficial tension (Liquid/Gas) measurements",
    "Contact angle (Liquid/Solid) measurements",
    "Rising or pendant drop modes",
    "Sessile drop or captive bubble modes",
    "Drop volume/Area regulation",
    "Dilatational interfacial rheology measurements",
    "Viscoelastic modulus determination",
    "Nonexplosive gas and Supercritical CO₂ compatible"
  ],

   applications : [
    {
      title: "Enhanced Oil Recovery (EOR)",
      description: "Interfacial tension and contact angle measurements for optimizing surfactant formulations and understanding oil-water-rock interactions under reservoir conditions."
    },
    {
      title: "Supercritical CO₂",
      description: "Surface and interfacial characterization with supercritical carbon dioxide for CO₂ injection, enhanced recovery, and carbon capture applications."
    },
    {
      title: "Petroleum & Bitumen Experiments",
      description: "High-temperature and high-pressure analysis of crude oil, bitumen, and heavy oil interfacial properties for production and processing optimization."
    },
    {
      title: "Smelt Polymer",
      description: "Surface tension and interfacial rheology measurements of polymer melts at elevated temperatures for materials processing and quality control."
    }
  ],

   specifications : [
    { parameter: "Maximum Temperature", value: "Up to 200°C" },
    { parameter: "Maximum Pressure", value: "Up to 700 bar" },
    { parameter: "Certification", value: "CETIM certified design" },
    { parameter: "Measurement Modes", value: "Pendant/Rising drop, Sessile drop, Captive bubble" },
    { parameter: "Interfacial Tension", value: "Liquid/Liquid interfaces" },
    { parameter: "Surface Tension", value: "Liquid/Gas interfaces" },
    { parameter: "Contact Angle", value: "Liquid/Solid interfaces" },
    { parameter: "Rheology", value: "Dilatational interfacial rheology & viscoelastic modulus" },
    { parameter: "Volume Control", value: "Drop volume/Area regulation" },
    { parameter: "Gas Compatibility", value: "Nonexplosive gas & Supercritical CO₂" }
  ],

  measurementCapabilities : [
    {
      icon: Flame,
      title: "Surface & Interfacial Tension",
      description: "Measure both liquid/gas surface tension and liquid/liquid interfacial tension under extreme conditions."
    },
    {
      icon: Gauge,
      title: "Contact Angle",
      description: "Characterize wettability and liquid/solid interactions at high temperature and pressure."
    },
    {
      icon: Zap,
      title: "Interfacial Rheology",
      description: "Study viscoelastic properties and interfacial modulus for comprehensive interface characterization."
    }
  ],
}

export const trackertensiometer = {
  
   measurements : [
    "Pendant drop or bubble",
    "Rising drop or bubble",
    "Sessile drop",
    "Captive drop or bubble",
    "Temperature",
    "Pressure",
    "Surface tension (liquid/gas)",
    "Interfacial tension (liquid/liquid)",
    "Adsorption/desorption kinetics",
    "Contact angle (liquid/solid)",
    "Dynamic contact angle",
    "Interfacial Dilatational Rheology",
    "Viscoelastic modulus",
    "Coefficient of rigidity",
    "Automatic CMC"
  ],

   applications : [
    {
      title: "Crude oil",
      description: "Emulsion stability for separation, influence of surfactants for EOR, dynamic contact angle between oil/rock/liquid phases."
    },
    {
      title: "Cosmetics",
      description: "Foam/emulsion stability, formulation, dynamic contact angle."
    },
    {
      title: "Pharmaceuticals",
      description: "Encapsulation, gas solubility, emulsion stability."
    },
    {
      title: "Food",
      description: "Food foams properties, stability of frozen emulsion (ice cream), influence of proteins, sugar or alcohol impact on the bubbles' size."
    },
    {
      title: "Fuel & Bitumen",
      description: "Wettability, emulsion properties, dynamic contact angle."
    },
    {
      title: "Lubricant",
      description: "Contact angle between lubricant/material, influence of surfactants on the wettability."
    }
  ],

   modules : [
    {
      title: "Dense Phase Exchange module",
      description: "A double pump exchanges the liquid in the cuvette by another liquid while keeping the volume of the drop or bubble constant. The phase exchange can be automated or controlled manually. All regulations can be carried out during phase exchange.",
      image: "/images/products/dense-phase-exchange-module.avif"
    },
    {
      title: "Drop Phase Exchange module",
      description: "A double injection system exchanges the liquid or gas in the drop or bubble by another liquid or gas while keeping the volume of the drop or bubble constant. All types of measurements can be performed during phase exchange.",
      image: "/images/products/drop-phase.avif"
    },
    {
      title: "CMC",
      description: "An Automated critical micelle concentration measurement system is added to TRACKER™ standard. A second injection system allows to measure up to 4 solutions of different concentrations. The injected volume and concentration are determined by an algorithm that calculates the concentration steps in order to optimise the accuracy of the CMC determination. The drop volume control allows the volume of the drop to be automatically adjusted according to the concentration.",
      image: "/images/products/tracker-cmc.avif"
    },
    {
      title: "Piezoelectric module",
      description: "A piezoelectric ceramic is added to TRACKER™ standard to achieve an oscillation frequency up to 10 Hz.",
      image: "/images/products/TRACKER-piezoelectric-module.avif"
    },
    {
      title: "Pressure Cell 200°C/200bars",
      description: "A removable Pressure Cell for High Temperature and High Pressure measurements can be adapted to TRACKER™ standard. All measurements with pendant drop or rising drop, sessile drop or capture bubble can be performed.",
      image: "/images/products/TRACKER-pressure-cell.avif"
    },
    {
      title: "Pressure Sensor",
      description: "The sensor measures the hydrostatic pressure above the bubble in liquid or the pressure of a bubble of air in air (soap bubble). The pressure sensor is a good tool to characterize that a membrane has formed at the surface and that the interface is no more \"liquid\". Combined with the piezoelectric cell, the Pressure sensor is also used to measure surface tension at High frequency oscillations.",
      image: "/images/products/TRACKER-pressure-sensor.avif"
    }
  ],

  moduleFeatures : [
    "Phase exchange",
    "Piezoelectric cell for higher frequency oscillation",
    "Pressure sensor to measure Laplace pressure in the bubble",
    "Automatic CMC",
    "Pressure Cell 200°C/200bar"
  ],
}
