

export interface Article {
  title: string;
  category: string;
  date?: string;
  readTime?: string;
  media?: string;
  excerpt?: string;
  pdfurl?: string;
}

export const articles: Article[] = [
  {
    title: "Introducing TRACKER™ AI: Next-Generation Surface Tension Analysis",
    excerpt:
      "Our latest AI-powered surface tension analyzer brings unprecedented accuracy and automation to interface science research.",
    category: "newsletter",
    date: "2024-03-15",
    readTime: "5 min read",
    media: "/pdf/TECLIS Newsletter 2025-08.pdf",
    pdfurl: "/pdf/TECLIS Newsletter 2025-08.pdf",
  },
  {
    title: "Breakthrough in Foam Stability Research Published in Nature",
    excerpt:
      "Teclis instruments contribute to groundbreaking research on foam stability mechanisms, published in Nature Materials.",
    category: "scientific_papers",
    date: "2024-03-10",
    readTime: "8 min read",
    media: "/news/nature-publication.jpg",
  },
  {
    title:
      "Teclis Scientific at European Colloid & Interface Society Conference",
    excerpt:
      "Join us at ECIS 2024 in Barcelona where we'll showcase our latest innovations and present cutting-edge research.",
    category: "events",
    date: "2024-03-05",
    readTime: "3 min read",
    media: "/news/ecis-conference.jpg",
  },
  {
    title: "Partnership with Leading Pharmaceutical Company Announced",
    excerpt:
      "Major pharmaceutical company selects Teclis instruments for their global research and development operations.",
    category: "company",
    date: "2024-02-28",
    readTime: "4 min read",
    media: "/news/pharma-partnership.jpg",
  },
  {
    title: "New Application Note: Surface Tension in Food Emulsions",
    excerpt:
      "Comprehensive guide to measuring and optimizing surface tension in food emulsion systems for better product stability.",
    category: "scientific_papers",
    date: "2024-02-20",
    readTime: "6 min read",
    media: "/news/food-emulsions.jpg",
  },
  {
    title: "FOAMSCAN™ Software Update: Enhanced Analysis Capabilities",
    excerpt:
      "Latest software update includes advanced foam characterization algorithms and improved user interface design.",
    category: "newsletter",
    date: "2024-02-15",
    readTime: "4 min read",
    media: "/news/foamscan-update.jpg",
  },
  {
    title: "Teclis Scientific Wins Innovation Award at Analytica 2024",
    excerpt:
      "Our RHEOSCAN™ Interface Rheometer recognized for outstanding innovation in analytical instrumentation.",
    category: "company",
    date: "2024-02-10",
    readTime: "3 min read",
    media: "/news/innovation-award.jpg",
  },
  {
    title: "Webinar Series: Advanced Interface Science Techniques",
    excerpt:
      "Join our monthly webinar series featuring expert presentations on cutting-edge interface science applications.",
    category: "events",
    date: "2024-02-01",
    readTime: "2 min read",
    media: "/news/webinar-series.jpg",
  },
  {
    title:
      "How to measure the interfacial properties of solid oils with TRACKER™",
    excerpt:
      "TRACKER™ enables accurate surface-tension measurements of solidifying oils by heating syringe and needle to maintain liquid state during analysis.",
    category: "application_notes",
    date: "",
    readTime: "",
    media: "/news/solid-oils-tracker.jpg",
  },
  {
    title: "Characterizing foams produced by an external device",
    excerpt:
      "FOAMSCAN™ analyzes foam from dispensers by quantifying liquid fraction and bubble-size distribution for hands-disinfectant applications.",
    category: "application_notes",
    date: "",
    readTime: "",
    media: "/news/2022AN6_Dia1.jpg",
  },
  {
    title: "The influence of experiment settings on foaming capacity",
    excerpt:
      "Gas-flow rate, frit porosity, stirring speed, and liquid volume strongly influence foaming time and wetness in FOAMSCAN™ measurements.",
    category: "application_notes",
    date: "",
    readTime: "",
    media: "/images/articles-img/2022AN5_impact.avif",
  },
  {
    title: "Standard error: five reasons you should check the drop profile",
    excerpt:
      "Residual-pattern analysis in TRACKER™ reveals non-Laplacian drops caused by vibrations, bubbles, dust, interfacial films, or moving contours.",
    category: "application_notes",
    date: "2022",
    readTime: "",
    media: "/images/articles-img/2022AN4_Standard-error.avif",
  },
  {
    title: "Interfacial Rheology: A Tool to Probe Interfaces",
    excerpt:
      "Oscillatory deformation reveals interfacial viscoelastic moduli, distinguishing surface-active interfaces from those with true viscoelastic behavior.",
    category: "application_notes",
    date: "",
    readTime: "",
    media: "/news/interfacial-rheology.jpg",
  },
  {
    title:
      "Impact of frequency, amplitude and concentration on interfacial viscoelastic modulus",
    excerpt:
      "Frequency, amplitude, and concentration govern interfacial elasticity and viscosity; E* varies with solicitation regime rather than being intrinsic.",
    category: "application_notes",
    date: "",
    readTime: "",
    media: "/news/VE-frequency-amplitude.jpg",
  },
  {
    title: "Interfacial rheology: micro and macro illustrations",
    excerpt:
      "Interfacial viscoelasticity links molecular adsorption and macroscopic foam/emulsion stability; higher elasticity improves resistance to coalescence.",
    category: "application_notes",
    date: "",
    readTime: "",
    media: "/news/micro-macro-rheology.jpg",
  },
  {
    title: "Dispersity: an indicator to classify the foam dissipation",
    excerpt:
      "Bubble-size dispersity distinguishes coarsening-driven foam decay from coalescence-driven decay in FOAMSCAN™ studies.",
    category: "application_notes",
    date: "",
    readTime: "",
    media: "/news/foam-dispersity.jpg",
  },
  {
    title:
      "The deposition of a monolayer of phospholipids at the oil–water interface",
    excerpt:
      "Phospholipid monolayers at oil–water interfaces model emulsions and lipid droplets, governed by molecular packing and interfacial dynamics.",
    category: "application_notes",
    date: "",
    readTime: "",
    media: "/news/phospholipid-monolayer.jpg",
  },
  {
    title: "How to control the surface pressure of an interface",
    excerpt:
      "Controlled compression/expansion with TRACKER™ adjusts surface pressure, enabling studies of monolayer packing, adsorption, and rheology.",
    category: "application_notes",
    date: "",
    readTime: "",
    media: "/news/surface-pressure-control.jpg",
  },
  {
    title: "How to determine the maximum surface pressure of a molecule",
    excerpt:
      "Compression–expansion cycles with TRACKER™ determine ΠMAX, identifying the pressure at which molecules desorb from interfaces.",
    category: "application_notes",
    date: "",
    readTime: "",
    media: "/news/max-surface-pressure.jpg",
  },
  {
    title: "How to determine the surface exclusion pressure of a molecule",
    excerpt:
      "Surface exclusion pressure (Πₑ) quantifies the upper limit allowing molecular insertion into lipid monolayers via adsorption-induced ΔΠ analysis.",
    category: "application_notes",
    date: "",
    readTime: "",
    media: "/news/surface-exclusion-pressure.jpg",
  },
  {
    title: "Newsletter August 2025 – FOAMSCAN™ HTMP",
    excerpt: "a remplir",
    category: "newsletter",
    date: "2025-08-27",
    readTime: "1 min read",
    media: "a remplir",
    pdfurl: "a remplir",
  },
  {
    title: "Oil crystallization monitored by the TRACKER™ at ESM2025",
    excerpt: "a remplir",
    category: "events",
    date: "2025-07-09",
    readTime: "0 min read",
    media: "/images/articles-img/videon1.mp4",
  },
  {
    title: "Meet us at Edible Soft Matter 2025 in Rennes (July 8–10)",
    excerpt: "a remplir",
    category: "events",
    date: "2025-06-24",
    readTime: "0 min read",
    media: "a remplir",
  },
  {
    title: "Newsletter March 2025",
    excerpt: "a remplir",
    category: "newsletter",
    date: "2025-03-06",
    readTime: "1 min read",
    media: "a remplir",
  },
  {
    title: "Measure the interfacial properties of solid oils with TRACKER™",
    excerpt: "a remplir",
    category: "application_notes",
    date: "2025-02-19",
    readTime: "1 min read",
    media: "a remplir",
  },
  {
    title: "BubbleStatistics™ software released for FOAMSCAN™ media analysis",
    excerpt: "a remplir",
    category: "company",
    date: "2024-05-17",
    readTime: "1 min read",
    media: "a remplir",
  },
  {
    title: "EUFOAM 2024 – Meet us in Dresden (June 30–July 4)",
    excerpt: "a remplir",
    category: "events",
    date: "2024-05-15",
    readTime: "0 min read",
    media: "a remplir",
  },
  {
    title:
      "Measure contact angles up to 200°C with TRACKER High Temperature Gonio Platform",
    excerpt: "a remplir",
    category: "application_notes",
    date: "2024-04-18",
    readTime: "1 min read",
    media: "a remplir",
  },
  {
    title: "Improve your Foam Analysis!",
    excerpt: "a remplir",
    category: "newsletter",
    date: "2024-03-21",
    readTime: "1 min read",
    media: "a remplir",
  },
  {
    title: "Hiring: Business-oriented Scientist for TECLIS Europe",
    excerpt: "a remplir",
    category: "company",
    date: "2024-01-15",
    readTime: "1 min read",
    media: "a remplir",
  },
  {
    title: "A Great French-German scientific Team!",
    excerpt: "a remplir",
    category: "company",
    date: "2023-07-20",
    readTime: "1 min read",
    media: "a remplir",
  },
  {
    title: "Meet us at ISFRS 2023",
    excerpt: "a remplir",
    category: "events",
    date: "2023-06-06",
    readTime: "1 min read",
    media: "a remplir",
  },
  {
    title: "March Newsletter – 2022 Publications",
    excerpt: "a remplir",
    category: "newsletter",
    date: "2023-03-15",
    readTime: "1 min read",
    media: "a remplir",
  },
  {
    title: "Happy New Year 2023!",
    excerpt: "a remplir",
    category: "company",
    date: "2023-01-18",
    readTime: "0 min read",
    media: "a remplir",
  },
  {
    title: "Using FOAMSCAN to characterize foams produced by any device",
    excerpt: "a remplir",
    category: "application_notes",
    date: "2022-11-14",
    readTime: "1 min read",
    media: "medias/articles-img/using-foamscan-to-characterize.avif",
  },
  {
    title: "Job opportunity Alert!",
    excerpt: "a remplir",
    category: "company",
    date: "2022-08-03",
    readTime: "1 min read",
    media: "a remplir",
  },
  {
    title: "WUR 2nd Edible Soft Matter Workshop & Conference",
    excerpt: "a remplir",
    category: "events",
    date: "2022-06-27",
    readTime: "0 min read",
    media: "a remplir",
  },
  {
    title: "TRACKER™ in Drug Delivery formulation",
    excerpt: "a remplir",
    category: "application_notes",
    date: "2022-06-21",
    readTime: "1 min read",
    media: "a remplir",
  },
  {
    title: "Neutrons dive into foam: scattering and reflectivity",
    excerpt: "a remplir",
    category: "scientific_papers",
    date: "2022-05-11",
    readTime: "1 min read",
    media: "a remplir",
  },
  {
    title: "April 2022 Newsletter – Technical Focus",
    excerpt: "a remplir",
    category: "newsletter",
    date: "2022-04-11",
    readTime: "1 min read",
    media: "a remplir",
  },
  {
    title: "Become an expert in Liquid foams and emulsions",
    excerpt: "a remplir",
    category: "newsletter",
    date: "2022-01-21",
    readTime: "1 min read",
    media: "a remplir",
  },
  {
    title: "January 2022 Newsletter",
    excerpt: "a remplir",
    category: "newsletter",
    date: "2022-01-19",
    readTime: "1 min read",
    media: "a remplir",
  },
  {
    title: "Only Lyon Rheology!",
    excerpt: "a remplir",
    category: "events",
    date: "2022-01-12",
    readTime: "1 min read",
    media: "a remplir",
  },
  {
    title: "Happy 2022 !",
    excerpt: "a remplir",
    category: "company",
    date: "2022-01-12",
    readTime: "0 min read",
    media: "a remplir",
  },
  {
    title: "6-month Internship – Solubility of Gas in Liquid cell",
    excerpt: "a remplir",
    category: "company",
    date: "2021-12-02",
    readTime: "1 min read",
    media: "a remplir",
  },
  {
    title: "New Jetscan has arrived!",
    excerpt: "a remplir",
    category: "company",
    date: "2021-11-09",
    readTime: "0 min read",
    media: "a remplir",
  },
  {
    title: "Fête de la Science – TECLIS",
    excerpt: "a remplir",
    category: "events",
    date: "2021-10-11",
    readTime: "1 min read",
    media: "a remplir",
  },
  {
    title: "Petrophase 2021 – Follow us",
    excerpt: "a remplir",
    category: "events",
    date: "2021-06-02",
    readTime: "0 min read",
    media: "a remplir",
  },
  {
    title: "Best wishes for 2021",
    excerpt: "a remplir",
    category: "company",
    date: "2021-01-15",
    readTime: "0 min read",
    media: "a remplir",
  },
  {
    title: "Dispersity parameter for foam dissipation",
    excerpt: "a remplir",
    category: "application_notes",
    date: "2021-01-15",
    readTime: "0 min read",
    media: "a remplir",
  },
  {
    title: "High-frequency interface measurement device",
    excerpt: "a remplir",
    category: "scientific_papers",
    date: "2020-11-16",
    readTime: "1 min read",
    media: "a remplir",
  },
  {
    title: "SoFiA Project Online Workshop",
    excerpt: "a remplir",
    category: "events",
    date: "2020-10-26",
    readTime: "1 min read",
    media: "a remplir",
  },
  {
    title: "October 2020 Newsletter",
    excerpt: "a remplir",
    category: "newsletter",
    date: "2020-10-18",
    readTime: "0 min read",
    media: "a remplir",
  },
  {
    title: "Soap film interfacial characterization",
    excerpt: "a remplir",
    category: "scientific_papers",
    date: "2020-06-30",
    readTime: "1 min read",
    media: "a remplir",
  },
  {
    title: "Plos Biology – Bacterial multicellularity",
    excerpt: "a remplir",
    category: "scientific_papers",
    date: "2020-06-24",
    readTime: "1 min read",
    media: "a remplir",
  },
  {
    title: "Newsletter – May 2020",
    excerpt: "a remplir",
    category: "newsletter",
    date: "2020-05-08",
    readTime: "0 min read",
    media: "a remplir",
  },
  {
    title: "Foam Up Research Project",
    excerpt: "a remplir",
    category: "scientific_papers",
    date: "2020-04-12",
    readTime: "1 min read",
    media: "a remplir",
  },
  {
    title: "January Newsletter 2020",
    excerpt: "a remplir",
    category: "newsletter",
    date: "2020-02-05",
    readTime: "0 min read",
    media: "a remplir",
  },
  {
    title: "Phospholipids at oil–water interface",
    excerpt: "a remplir",
    category: "scientific_papers",
    date: "2020-01-21",
    readTime: "1 min read",
    media: "a remplir",
  },
  {
    title: "Challenge the hardest experimental conditions!",
    excerpt: "a remplir",
    category: "company",
    date: "2020-01-07",
    readTime: "1 min read",
    media: "a remplir",
  },
  {
    title: "Soap films and the future",
    excerpt: "a remplir",
    category: "scientific_papers",
    date: "2019-08-28",
    readTime: "0 min read",
    media: "a remplir",
  },
  {
    title: "Merger of a bubble and a soap film",
    excerpt: "a remplir",
    category: "scientific_papers",
    date: "2019-08-28",
    readTime: "0 min read",
    media: "a remplir",
  },
  {
    title: "July 2019 Newsletter",
    excerpt: "a remplir",
    category: "newsletter",
    date: "2019-07-30",
    readTime: "1 min read",
    media: "a remplir",
  },
  {
    title: "Bubble & Drop 2019 – Did you miss it?",
    excerpt: "a remplir",
    category: "events",
    date: "2019-07-01",
    readTime: "1 min read",
    media: "a remplir",
  },
  {
    title: "Bubble and Drops...",
    excerpt: "a remplir",
    category: "events",
    date: "2019-06-19",
    readTime: "1 min read",
    media: "a remplir",
  },
  {
    title: "New strategy to treat crude oil",
    excerpt: "a remplir",
    category: "scientific_papers",
    date: "2019-06-19",
    readTime: "1 min read",
    media: "a remplir",
  },
  {
    title: "Bubble & Drop 2019 is coming!",
    excerpt: "a remplir",
    category: "events",
    date: "2019-02-11",
    readTime: "1 min read",
    media: "a remplir",
  },
  {
    title: "SoFia – From bubbles to solar fuel",
    excerpt: "a remplir",
    category: "scientific_papers",
    date: "2019-02-05",
    readTime: "1 min read",
    media: "a remplir",
  },
  {
    title: "Two Drop Tensiometer in mass transfer study",
    excerpt: "a remplir",
    category: "scientific_papers",
    date: "2018-10-04",
    readTime: "1 min read",
    media: "a remplir",
  },
  {
    title: "Evidence of a Desorption Barrier",
    excerpt: "a remplir",
    category: "scientific_papers",
    date: "2018-07-23",
    readTime: "1 min read",
    media: "a remplir",
  },
  {
    title: "Special High Pressure / Temperature",
    excerpt: "a remplir",
    category: "company",
    date: "2018-04-01",
    readTime: "1 min read",
    media: "a remplir",
  },
  {
    title: "Newsletter January 2018",
    excerpt: "a remplir",
    category: "newsletter",
    date: "2018-02-08",
    readTime: "1 min read",
    media: "a remplir",
  },
  {
    title: "From Flower to Perfume formulation",
    excerpt: "a remplir",
    category: "scientific_papers",
    date: "2017-11-13",
    readTime: "1 min read",
    media: "a remplir",
  },
  {
    title: "Teclis & University of Petroleum in China Seminar",
    excerpt: "a remplir",
    category: "events",
    date: "2017-10-10",
    readTime: "1 min read",
    media: "a remplir",
  },
  {
    title: "Brand new Two-drop tensiometer!",
    excerpt: "a remplir",
    category: "company",
    date: "2017-07-25",
    readTime: "1 min read",
    media: "a remplir",
  },
  {
    title: "Bubble & Drop conference: success!",
    excerpt: "a remplir",
    category: "events",
    date: "2017-07-04",
    readTime: "1 min read",
    media: "a remplir",
  },
  {
    title: "Bubble & Drop program online!",
    excerpt: "a remplir",
    category: "events",
    date: "2017-06-16",
    readTime: "1 min read",
    media: "a remplir",
  },
];
